scheduling:
  userScheduler:
    enabled: false
proxy:
  secretToken: "a67af951e0204d8df9945ca71fc19be6"
  service:
    type: ClusterIP
hub:
  config:
    JupyterHub:
      authenticator_class: ldapauthenticator.LDAPAuthenticator
    LDAPAuthenticator:
      allowed_groups:
        - cn=Users,ou=JupyterHub,ou=Groups,dc=sema,dc=df,dc=gov,dc=br
      bind_dn_template:
        - cn={username},ou=People,dc=sema,dc=df,dc=gov,dc=br
      escape_userdn: false
      lookup_dn: true
      lookup_dn_search_user: cn=usersync,ou=People,dc=sema,dc=df,dc=gov,dc=br
      lookup_dn_search_password: usersync
      lookup_dn_user_dn_attribute: cn
      server_address: ldap://openldap-svc.openldap-bigdata.svc.cluster.local:389
      user_attribute: cn
      user_search_base: ou=People,dc=sema,dc=df,dc=gov,dc=br
      use_ssl: true
singleuser:
  # Defines the default image
  image:
    name: jupyter/minimal-notebook
    tag: 2343e33dec46
  serviceAccountName: hub
  profileList:
    - display_name: "Minimal environment"
      description: "To avoid too much bells and whistles: Python."
      default: true
    - display_name: "Datascience environment"
      description: "If you want the additional bells and whistles: Python, R, and Julia."
      kubespawner_override:
        image: jupyter/datascience-notebook:2343e33dec46
    - display_name: "Spark environment"
      description: "The Jupyter Stacks spark image!"
      kubespawner_override:
        image: jupyter/all-spark-notebook:2343e33dec46
    - display_name: "Learning Data Science"
      description: "Datascience Environment with Sample Notebooks"
      kubespawner_override:
        image: jupyter/datascience-notebook:2343e33dec46
        lifecycle_hooks:
          postStart:
            exec:
              command:
                - "sh"
                - "-c"
                - >
                  gitpuller https://github.com/data-8/materials-fa17 master materials-fa;



      
