apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: trino-worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: trino-worker
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50