apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkb2NrZXIuYXBwLnNlbWEuZGYuZ292LmJyIjogewoJCQkiYXV0aCI6ICJZV1J0YVc0NlUybHpaR2xoWm1GelpUST0iCgkJfSwKCQkiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogewoJCQkiYXV0aCI6ICJabUZpYVdGdWIyRTZNamt3TVRrMyIKCQl9Cgl9Cn0K
---
apiVersion: batch/v1
kind: Job
metadata:
  name: trino-metastore-initschema
spec:
  template:
    spec:
      imagePullSecrets:
          - name: regcred
      containers:
      - name: hivemeta
        image: fabianoa/hive-metastore:3.0.0
        command: ["/opt/apache-hive-metastore-3.0.0-bin/bin/schematool"]
        args: ["--verbose" ,"-initSchema" , "-dbType", "mysql" , "-userName", "root",
          "-passWord", "mypass" , "-url", "jdbc:mysql://trino-metastore-db:3306/metastore_db?createDatabaseIfNotExist=true"]
      restartPolicy: Never
  backoffLimit: 2
