---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pv-claim
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: es-ranger
spec:
  ports:
  - port: 9200
    targetPort: 9200
  selector:
    app: es-ranger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-ranger
spec:
  selector:
    matchLabels:
      app: es-ranger
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: es-ranger
    spec:
      containers:
      - name: es-ranger
        image: "docker.elastic.co/elasticsearch/elasticsearch:7.12.1"
        env:
        - name: discovery.type
          value: single-node
        - name: xpack.security.enabled
          value: "false" 
        ports:
        - containerPort: 9200
          name: es-ranger
        volumeMounts:
        - name: es-ranger
          mountPath: /usr/share/elasticsearch/data
        resources:
          requests:
            memory: "4G"
            cpu: 2
      volumes:
      - name: es-ranger
        persistentVolumeClaim:
          claimName: es-pv-claim
