apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-ranger-pv-claim
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
      
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-ranger-creds
type: Opaque
stringData:
  password: 'postgres'

---
apiVersion: v1
kind: Service
metadata:
  name: ranger-db
spec:
  ports:
  - port: 13306
    targetPort: 3306
  selector:
    app: psql01
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql01
spec:
  selector:
    matchLabels:
      app: psql01
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: psql01
    spec:
      containers:
      - name: psql01
        image: "postgres:13"
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-ranger-creds
              key: password
        ports:
        - containerPort: 5432
          name: psql01
        volumeMounts:
        - name: postgres-for-ranger
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "4G"
            cpu: 2
      volumes:
      - name: postgres-for-ranger
        persistentVolumeClaim:
          claimName: postgres-ranger-pv-claim
